include theos/makefiles/common.mk

TWEAK_NAME = WANuntius
WANuntius_FILES = $(wildcard *.xm)
WANuntius_FRAMEWORKS = UIKit CoreGraphics
WANuntius_PRIVATE_FRAMEWORKS = NotificationsUI ChatKit AppSupport
WANuntius_LIBRARIES = rocketbootstrap

include $(THEOS_MAKE_PATH)/tweak.mk


